
version: "3"

services:
  bot:
    build:
      context: "."
      dockerfile: Dockerfile
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ".:/src"
    restart: always