"""Add setter username

Revision ID: cd9f3f359db1
Revises: efa327561105
Create Date: 2022-02-06 13:55:24.170817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd9f3f359db1'
down_revision = 'efa327561105'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('setter_username', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'setter_username')
    # ### end Alembic commands ###
